version: '3'

services:
  mariadb:
    image: wachira90/mariadb:10.2-debian-10
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password

  app:
    tty: true
    image: wachira90/laravel:8-debian-10
    container_name: app
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    ports:
      - 8088:3000
    volumes:
      - ./:/app
